version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:14
    container_name: zksync-postgres-bsc
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-your_secure_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (用于缓存)
  redis:
    image: redis:7-alpine
    container_name: zksync-redis-bsc
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ZKSync 服务器
  zksync-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: zksync-server-bsc
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # BSC 网络配置
      L1_CHAIN_ID: ${L1_CHAIN_ID:-97}
      L1_RPC_URL: ${L1_RPC_URL:-https://bsc-testnet-dataseed.bnbchain.org}
      
      # 数据库配置
      DATABASE_URL: postgres://postgres:${DB_PASSWORD:-your_secure_password}@postgres:5432/${DB_NAME:-zk_bsc_testnet}
      
      # Redis 配置
      REDIS_URL: redis://redis:6379
      
      # 服务配置
      API_WEB3_JSON_RPC_HTTP_PORT: 3050
      API_WEB3_JSON_RPC_WS_PORT: 3051
      API_PROMETHEUS_PORT: 3312
      API_HEALTHCHECK_PORT: 3081
      
      # 钱包配置
      OPERATOR_PRIVATE_KEY: ${OPERATOR_PRIVATE_KEY}
      GOVERNOR_PRIVATE_KEY: ${GOVERNOR_PRIVATE_KEY}
      
      # 日志配置
      RUST_LOG: ${RUST_LOG:-info}
      RUST_BACKTRACE: 1
    ports:
      - "3050:3050"  # HTTP API
      - "3051:3051"  # WebSocket API
      - "3081:3081"  # Health check
      - "3312:3312"  # Prometheus metrics
    volumes:
      - ./chains:/app/chains
      - ./configs:/app/configs
      - zksync_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: zksync-nginx-bsc
    restart: unless-stopped
    depends_on:
      - zksync-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - nginx_logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Prometheus 监控
  prometheus:
    image: prom/prometheus:latest
    container_name: zksync-prometheus-bsc
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

  # Grafana 仪表板
  grafana:
    image: grafana/grafana:latest
    container_name: zksync-grafana-bsc
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  zksync_data:
    driver: local
  nginx_logs:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  default:
    name: zksync-bsc-network