services:



  postgres:
    image: "postgres:14"
    command: postgres -c 'max_connections=1000'
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    environment:
      # We bind only to 127.0.0.1, so setting insecure password is acceptable here
      - POSTGRES_PASSWORD=notsecurepassword

  # This is specific to runner


volumes:
  postgres-data:
  reth-data:
